### PR TITLE
Don't show an full-screen overlay for warnings - only for errors

### PR DESCRIPTION
**Pull request by helenb**
### What is the context of this PR?

When running `honcho start` I noticed that a full-screen overlay *in the browser* (from webpack dev server) was appearing for warning messagess in the font-end tooling. This is obstructive if there are warnings appearing all the time, so this updates the config to only show the overlay message for errors.

### How to review

Run your local build, and use `honcho start` to start the dev server and the front-end tooling. Although there is a warning about a deprecated package, this should not appear in a full-screen overlay. Compare with the `main` branch where you should see the overlay.

See screenshot in the comment below for how the full-screen overlay appears with warnings on the main branch.

### Follow-up Actions

None

### CODE REVIEW

**Comment by zerolab** [comment]
@helenb I am seeing:

<details><summary>log</summary>

```shell
11:05:19 frontend.1  | > dis-wagtail@0.1.0 start:reload
11:05:19 frontend.1  | > webpack-dev-server
11:05:19 frontend.1  |
11:05:20 frontend.1  | <i> [webpack-dev-server] [HPM] Proxy created: () => true  -> http://localhost:8000
11:05:20 frontend.1  | <i> [webpack-dev-server] Project is running at:
11:05:20 frontend.1  | <i> [webpack-dev-server] Loopback: http://localhost:3000/
11:05:22 web.1       | Watching for file changes with StatReloader
11:05:22 web.1       | Performing system checks...
11:05:22 web.1       |
11:05:22 web.1       | System check identified no issues (0 silenced).
11:05:22 scheduler.1 | [2024-12-05 11:05:22,995][23][INFO][apscheduler.scheduler] Adding job tentatively -- it will be properly scheduled when the scheduler starts
11:05:22 scheduler.1 | [2024-12-05 11:05:22,996][23][INFO][apscheduler.scheduler] Adding job tentatively -- it will be properly scheduled when the scheduler starts
11:05:22 scheduler.1 | [2024-12-05 11:05:22,996][23][INFO][apscheduler.scheduler] Added job "publish_bundles" to job store "default"
11:05:22 scheduler.1 | [2024-12-05 11:05:22,996][23][INFO][apscheduler.scheduler] Added job "publish_scheduled_without_bundles" to job store "default"
11:05:22 scheduler.1 | [2024-12-05 11:05:22,996][23][INFO][apscheduler.scheduler] Scheduler started
11:05:23 web.1       | December 05, 2024 - 11:05:23
11:05:23 web.1       | Django version 5.1.3, using settings 'cms.settings.dev'
11:05:23 web.1       | Starting development server at http://0.0.0.0:8000/
11:05:23 web.1       | Quit the server with CONTROL-C.
11:05:23 web.1       |
11:05:23 frontend.1  | Entrypoint main 701 KiB = css/main.css 54.1 KiB js/main.js 647 KiB
11:05:23 frontend.1  |
11:05:23 frontend.1  | WARNING in ./cms/static_src/sass/main.scss (./cms/static_src/sass/main.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].use[3]!./cms/static_src/sass/main.scss)
11:05:23 frontend.1  | Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
11:05:23 frontend.1  | Deprecation The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
11:05:23 frontend.1  |
11:05:23 frontend.1  | More info: https://sass-lang.com/d/legacy-js-api
11:05:23 frontend.1  |  @ ./cms/static_src/sass/main.scss
11:05:23 frontend.1  |  @ ./cms/static_src/javascript/main.js 2:0-27
11:05:23 frontend.1  |
11:05:23 frontend.1  | webpack compiled with 1 warning in 2950 ms
```

</details> 

which is the same as on `main`. What am I missing?

**Comment by helenb** [comment]
> @helenb I am seeing:
> 
> log
> which is the same as on `main`. What am I missing?

Hi @zerolab is that output from your terminal? This change is not to update what gets logged there, but to update the full-screen overlay in the browser which is a bit intrusive:

Screenshot 2024-12-05 at 12 17 15

**Comment by zerolab** [comment]
ah, that explains it. in this case LGTM!

**Review by zerolab — APPROVED** [review]

**Review by MebinAbraham — APPROVED** [review]

**Review by sanjeevz3009 — COMMENTED** [review]
Reviewed! Annoying overlay vanished =)

**Pull request merged**
