### PR TITLE
Replace Docker Desktop setup with Colima

### PR DESCRIPTION
**Pull request by MebinAbraham**
### What is the context of this PR?

Replaced the requirement for Docker and Docker Compose via Docker Desktop with [Colima](https://github.com/abiosoft/colima).

Before installing Colima, make sure you uninstall Docker Desktop. If you run into issue, please first check [the troubleshooting guide.
](https://github.com/ONSdigital/dp-operations/blob/main/troubleshooting/fixing-colima-related-errors.md)

### How to review

Ensure the project can be set up as-is with Colima.

### CODE REVIEW

**Review by zerolab — APPROVED** [review]
The dependency note LGTM.

I wonder if we want the 

> Before installing Colima, make sure you uninstall Docker Desktop. If you run into issue, please first check [the troubleshooting guide](https://github.com/ONSdigital/dp-operations/blob/main/troubleshooting/fixing-colima-related-errors.md).

line there as well, at least in the transitionary period

**Review by AdamHawtin — APPROVED** [review]

**Comment by MebinAbraham** [comment]
> The dependency note LGTM.
> 
> I wonder if we want the
> 
> > Before installing Colima, make sure you uninstall Docker Desktop. If you run into issue, please first check [the troubleshooting guide](https://github.com/ONSdigital/dp-operations/blob/main/troubleshooting/fixing-colima-related-errors.md).
> 
> line there as well, at least in the transitionary period

That was more for compliance. They can co-exist: https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#can-it-run-alongside-docker-for-mac

**Review by kacperpONS — APPROVED** [review]
It might for dev's convenience to add a note about the [Colima autostart](https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#does-colima-support-autostart).
That should probably live in the linked document not here, so I'm not going to block on this.

**Comment by AWitcherONS** [comment]
Instructions Good!
Make Brilliant! python version picking up 
Make test produces error

**Review by sanjeevz3009 — COMMENTED** [review]
Read!

**Pull request merged**
